---
bio: PhD student studying vector-borne diseases 

email: ""
highlight_name: true

organizations:
- name: University of Tennessee - Knoxville
  url: https://epp.tennessee.edu/
role: PhD Student
social:

- icon: twitter
  icon_pack: fab
  link: https://twitter.com/CoreyAllenDay
- icon: linkedin
  icon_pack: fab
  link: https://www.linkedin.com/in/coreyaday/
- icon: researchgate
  icon_pack: ai
  link: https://www.researchgate.net/profile/Corey-Day
- icon: google-scholar
  icon_pack: ai
  link: https://scholar.google.com/citations?hl=en&user=jU4xmN4AAAAJ&view_op=list_works&sortby=pubdate
superuser: true
title: Corey Day
---
Hello! My name is Corey, and this is my website. My primary motivation for building this site is to create a space where I can share reader-friendly versions of my scientific work. Peer-reviewed scientific literature is often impenetrable for everyone except the select few who work in that field of study. If my research can be useful for people who want to protect themselves and their families from a disease, then I feel that those people have a right to access and understand that research. On this site, I will produce reader-friendly versions of my published research products that are light on jargon and briskly emphasize the main points of the work. 

A secondary goal for this website is to host tutorials for some of my workflows to help other scientists replicate processes that have been useful for me. Mostly, this will be limited to R tutorials, but I may also write some short guides for other work that I do (e.g., mosquito collection protocols). The internet is full of great resources for learning (especially when it comes to R), but I still come across the occasional task that is not well-documented online. I have benefited greatly from the work of others who produce learning resources online, so I want to pay it forward. 

